site_name: Toe•bias
site_url: https://www.toebias.com
theme:
 name: material
 features:
  - navigation.footer
 palette:
  primary: teal
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
 - glightbox
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/toebiasht/
    - icon: fontawesome/solid/paper-plane
      link: mailto:services@toebias.com
copyright: Copyright &copy; 2021 - 2024 Toe•bias
nav:
  - Home: index.md
  - Analytics and Visualization: data-analytics-and-visualization.md
  - Business Process Automation: business-process-automation.md
  - Custom Software Development: custom-software-development.md
  - Datascience as a service: datascience-as-a-service.md
  - Training: training.md
  - Consultancy: consultancy.md
  - Blog: https://blog.toebias.com/